version: "3.8"
services:
  golaundry:
    container_name: golaundry
    image: golaundry
    restart: always
    environment:
      POSTGRES_HOST: postgres-golaundry
      POSTGRES_PORT: 5432
    ports:
      - "8080:3000"
  postgres-golaundry:
    container_name: postgres-golaundry
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: golaundry
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
